### ISSUE TITLE
Manhattan plot of relative importance

### ISSUE THREAD

**Issue by Anitha-byt** [ArnovanHilten/GenNet#100]
Hello Arno,

When I generate the manhattan plots, I could see that in some plots  one/two SNPS having more than one relative importance.
I wonder why. I don't see any duplicate SNPs in my topology file.

I have attached an example of it. The snp rs74760710 and 10:33796516_CT_C being printed twice.
![Manhattan_relative_importance_SNPs (4)](https://github.com/ArnovanHilten/GenNet/assets/83635519/708dc1fb-3fa2-4a7b-86c2-4dd794ef4606)

**Comment by ArnovanHilten** [comment]
Dear Anitha, 

One of the reasons could be that this SNP is connected to multiple genes. The function plots the relative importance of every possible path (from output to input).

If this is not the case, or if you would like a feature where these paths are combined, then I can make some change, check for bugs or add features.

Best,

Arno
