### ISSUE TITLE
Usage of VEP annotation tool instead of ANNOVAR

### ISSUE THREAD

**Issue by ggokturkk** [ArnovanHilten/GenNet#83]
Hi Arno,
First of all, thank you for sharing this great work. I am currently trying to reproduce the A_to_Z.ipynb. However, some of the part code is I think hardcoded with only ANNOVAR. I directly used the VEP annotation tool and try to put its output to the topology step but got some errors because of (I guess) the different data structures inside the files (ANNOVAR_vs_VEP). I am thinking of converting the data structure of the VEP output to the ANNOVAR data structure as you wrote in the main code. Do you have any recommendations for this step?

Kind regards,
Gokhan

**Comment by ArnovanHilten** [comment]
Hi ggokturkk,

The gene layer part of the topology submodule is ANNOVAR specific. Did you encounter problems here or somewhere else? 
Could you link/post a snippet of your VEP output? I think I can help write a VEP equivalent or give some pointers. In the end you just want to generate a connectivity matrix in this step (or a toplogy.csv but you can derive one from the other).

Best,

Arno
