### ISSUE TITLE
The URL which install annovar does not exist

### ISSUE THREAD

**Issue by Resist4263** [ArnovanHilten/GenNet#85]
![image](https://user-images.githubusercontent.com/60375463/195336244-b386ade9-912f-45e4-97f1-c0f0c2d14050.png)
![image](https://user-images.githubusercontent.com/60375463/195336296-a3a0f017-a3db-4329-aa56-4b56d0e3c12a.png)
The URL which install annovar is valid.

**Comment by ArnovanHilten** [comment]
Hi @Resist4263 

Thank you for notifying me, I will update the link. In the meantime you can use this link to register and download annovar:

https://annovar.openbioinformatics.org/en/latest/user-guide/download/

Or directly to the registration form:

https://www.openbioinformatics.org/annovar/annovar_download_form.php

Best,

Arno

**Comment by Resist4263** [comment]
Okay, thanks. It works for me.
