### ISSUE TITLE
how to interpret results

### ISSUE THREAD

**Issue by lesyngenta** [ArnovanHilten/GenNet#93]
Hi Arno,

After I got the results 'connection_weights.csv', I don't know how to interpret that. Shall I look at the 'raw importance' column for the genes most correlated with a phenotype? I like the example figure "example_manhattan.png", but the GenNet.py plot only plots manhattan for SNPs instead of genes. 
One more question is about how to use ".npz" file in the training. Is there any example for the format of npz file?

Thanks,
Le

**Comment by ArnovanHilten** [comment]
Hey Le,

It is quite hard to make plots that work/look good for all the networks. If you post your connection_weights.csv I can provide you some code to plot the results. Did you check the other plotting options? You can use sunburst or layer_weight with the corresponding layer that you want to plot. These should also provide you some insight.

About the NPZ:

(https://github.com/ArnovanHilten/GenNet/blob/master/jupyter_notebooks/2_Define_connection_masks_simple_memory_efficient.ipynb). `The GenNet.py topology create_gene_network`  should provide also the equivalent .npz file for the topology.csv

The npz file is just a handy alternative to the topology.csv

In short:

    Dense layer with custom connections. The custom connections are defined by the mask input, a sparse (COO) connectivity matrix.

    # The matrix has the shape of (N_nodes_layer_1, N_nodes_layer_2).
    # It is a sparse matrix with zeros for no connections and ones if there is a connections. For example.


    #             output
    #           1 2 3 4 5
    # input 1 | 1 0 0 0 0 |
    # input 2 | 1 1 0 0 0 |
    # input 3 | 0 1 0 0 0 |
    # input 4 | 0 1 0 0 0 |
    # input 5 | 0 0 1 0 0 |
    # input 6 | 0 0 0 1 0 |
    # input 7 | 0 0 0 1 0 |


    # This connects the first two inputs (1,2) to the first neuron in the second layer.
    # Connects input 2,3 and 4 to output neuron 2.
    # Connects input 5 to output neuron 3
    # Connects input 6 and 7 o the 4th neuron in the subsequent layer
    # Connects nothing to the 5th neuron

If you have such a matrix in a numpy array you can simply use:

```
import numpy as np
a=np.eye(3)
import scipy.sparse
scipy.sparse.coo_matrix(a)
```


[or if the matrix is very large look at the examples here.
](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html)

[Here you can find some more information about the npz, file]

**Comment by ArnovanHilten** [comment]
Hi Le,

For some interpretation steps we calculate for every possible path (between input and output) the importance. This can be very large, especially if you have some densely connected layers. There are some ways to prune this, for example during each step between the layers we could remove the paths with (near) zero importance.

Can you post your error message and maybe a summary of your network? This would help to find a solution for you.

Best,

Arno

**Comment by lesyngenta** [comment]
Hi Arno,

Here is the network structure attached and the error message.

Thanks,
Le

***@***.***

**Comment by ArnovanHilten** [comment]
Ah the network is relativly small indeed. It should be no problem to ge the connection_weight.csv. I will investigate if there is a bug that causes the memory to be so high!

**Comment by lesyngenta** [comment]
Hi Arno,

Any idea? I found no matter how large the network is, if it only contains three layers (layer0-layer2), its ok. But if I add one more layer (layer3), then the connection_weight.csv cannot be created.

Thanks,
Le

**Comment by ArnovanHilten** [comment]
Hi Le,

I am working on a solution of your problem on this branch: https://github.com/ArnovanHilten/GenNet/tree/epistasis-interpretation .if you switch to this branch you can test it with `GenNet.py interpret get_weight_scores`. I need some more time to iron out all the bugs, so you can also wait (maybe a week) and then it will work for all networks.

Best,

Arno

**Comment by lesyngenta** [comment]
Thank you so much!

**Comment by lesyngenta** [comment]
Hi Arno,

I downloaded the new codes, but the connection_weight.csv couldn’t be created. I guess the reason is due to this function ‘def create_importance_csv(datapath, model, masks)’. I didn’t create masks file and all the 4 layers are listed in topology.csv. It seems that the create_importance_csv created huge matrix that excess computer memory. Is there any way to modify this function to fit into non-mask cases?

Thanks,
Le

**Comment by lesyngenta** [comment]
Hi Arno,

The new function doesn’t work for it can’t find train_args.json. But train_args.json was never generated.

python GenNet.py interpret -type get_weight_scores -resultpath /scratch-large/4-quarterly/s1198162/GenNet/results/GenNet_experiment_28_/
Traceback (most recent call last):
  File "GenNet.py", line 331, in <module>
    main()
  File "GenNet.py", line 36, in main
    interpret(args)
  File "/scratch-large/4-quarterly/s1198162/GenNet-epistasis-interpretation/GenNet_utils/Interpret.py", line 16, in interpret
    get_weight_scores(args)
  File "/scratch-large/4-quarterly/s1198162/GenNet-epistasis-interpretation/GenNet_utils/Interpret.py", line 29, in get_weight_scores
    model, masks = load_trained_network(args)
  File "/scratch-large/4-quarterly/s1198162/GenNet-epistasis-interpretation/GenNet_utils/Train_network.py", line 315, in load_trained_network
    args = load_train_arguments(args)
  File "/scratch-large/4-quarterly/s1198162/GenNet-epistasis-interpretation/GenNet_utils/Utility_functions.py", line 244, in load_train_arguments
    with open(args.resultpath + filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch-large/4-quarterly/s1198162/GenNet/results/GenNet_experiment_28_/train_args.json'

**Comment by lesyngenta** [comment]
Hi Arno,

Through the new function, I could create ‘weight_importance.npy’ but nothing was inside this file. I don’t know how to address that.

Thanks,
LE

**Comment by lesyngenta** [comment]
Close the issue for it was eventually solved. Thanks so much to Arno for the continuous guidance! It is lucky to meet such a responsible author!
